services:
  postgres:
    image: postgres:15
    container_name: lab1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: bookrentdb
    ports:
      - "5432:5432"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
